<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pubman_importer"
 *
 * Auto generated by Extension Builder 2014-08-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pubman Importer',
	'description' => 'imports data from Pubman',
	'category' => 'plugin',
	'author' => 'Ulf Seltmann',
	'author_email' => 'seltmann@ub.uni-leipzig.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.3.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'realurl' => '1.12.8-2.99.99',
		),
	),
);